os: linux
dist: xenial

language: ruby
rvm:
    - 2.6.3

env:
    # use of docker for python3.8 for running generate_about.py
    - IMGNAME=leonardsa/generate-about:1.0

services:
    - docker

branches:
    except:
        - master

before_install:
    - "cd scripts ; docker image build -t ${IMGNAME} ."

install:
    - "bundle install"

script:
    # run generate_about.py with bind to recover generated about.md
    - "docker run --mount type=bind,source=\"$(pwd)\",target=/tmp/transfer ${IMGNAME}"
    # run website generation
    - "./scripts/cibuild.sh"

after_success:
    # deploy website to master branch
    - "./scripts/deploy.sh"
