language: ruby
rvm:
    - 2.6.3

branches:
    except:
        - master

before_install:
    - "sudo apt update"
    - "sudo apt install python3.5"
    - "sudo apt install python3-pip"

install:
    - "bundle install"
    - "pip3 install gitpython --user"

script:
    - "python3 scripts/generate_about.py . ./resources/about_template.md 1"
    - "./scripts/cibuild.sh"

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local_dir: _site
    on:
        branch: develop

after_success:
    - script: "./scripts/deploy.sh"
