os: linux
dist: xenial

language: ruby
rvm:
    - 2.6.3

addons:
    apt:
        packages:
            - default-jre-headless  # jvm for plantuml
            - graphviz              # graphviz for dot and plantuml

env:
    # use of docker for python3.8 for running page modifying python scripts
    - IMGNAME=leonardsa/modify-pages:1.0

services:
    - docker

branches:
    except:
        - master

before_install:
    - "cd scripts ; docker image build -t ${IMGNAME} . ; cd .."

install:
    - "bundle install"

script:
    # run generate_about.py with bind to recover generated about.md
    - "docker run -e TRAVIS_BRANCH=$TRAVIS_BRANCH --mount type=bind,source=\"$(pwd)\",target=/tmp/transfer ${IMGNAME}"
    # build resources
    - "./scripts/build-resources.sh"
    # run website generation
    - "./scripts/cibuild.sh"

after_success:
    # deploy website to master branch
    - "./scripts/deploy.sh"
