language: ruby
rvm:
    - 2.6.3

before_install:
    - "sudo apt install python3.5"

install:
    - "pip install gitpython --user"

script:
    - "python3 scripts/generate_about.py . ./resources/about_template.md 1"
    - "./script/cibuild.sh"

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local_dir: _site
    on:
        branch: master
