language: ruby
rvm:
    - 2.6.3

branches:
    except:
        - master

before_install:
    - "sudo apt update"
    - "sudo apt install python3.9"
    - "sudo apt install python3-pip"
    - "pip3 install --upgrade pip"

install:
    - "bundle install"
    - "pip3 install GitPython --user"

script:
    - "python3 scripts/generate_about.py . ./resources/about_template.md 1 --branch $TRAVIS_BRANCH"
    - "./scripts/cibuild.sh"

after_success:
    - "./scripts/deploy.sh"
